version: '3.8'

services:

  mongo:
    container_name: docker_mongo_inventory
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: shop

    ports:
      - "27017:27017"

    volumes: 
      - $PWD/data:/data/db
      - $PWD/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  web:
    container_name: docker_node_inventory
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    volumes: 
      - /app/node_modules
      - $PWD/app:/app
    ports: 
      - "3002:3002"
